### ISSUE TITLE
gRPC via Spring Cloud Gateway

### ISSUE THREAD

**Issue by MilgoTest** [LogNet/grpc-spring-boot-starter#120]
Hey guys,

thanks for your update to support service discovery via Consul #119 . Now I'd like to combine Consul's service discovery with Spring Cloud Gateway to save some troubles getting the correct port via Consul.

I've created a grpc service and Consul discovered it as consul-service and grpc-consul-service. Now I tried to send a request:

```java
@Component
@Slf4j
public class HelloClient {

	private HelloServiceBlockingStub helloWorldServiceBlockingStub;

	@PostConstruct
	private void init() {
		ManagedChannel managedChannel = ManagedChannelBuilder.forTarget("localhost:8762/grpc-consul-service") // working: forAddress("localhost", 27156)
				.usePlaintext().build();

		helloWorldServiceBlockingStub = HelloServiceGrpc.newBlockingStub(managedChannel);
	}

	public GreetingResponse sayHello(String name) {
		try {
			GreetingRequest request = GreetingRequest.newBuilder().build();
			GreetingResponse greeting = helloWorldServiceBlockingStub.getGreeting(request);

			return greeting;
		} catch (StatusRuntimeException e) {
			log.error("Exception "+e+" occured.", e);
			throw e;
		}
	}
}
```

But I get an exception:
```
2019-06-04 16:01:07.742 ERROR [consul-lognet-client,f8868fc0915b80f5,f8868fc0915b80f5,true] 8144 --- [nio-8080-exec-3] d.w.consullognetclient.HelloClient       : Exception io.grpc.StatusRuntimeException: INTERNAL: http2 exception occured.

io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233) ~[grpc-stub-1.20.0.jar:1.20.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214) ~[grpc-stub-1.20.0.jar:1.20.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139) ~[grpc-stub-1.20.0.jar:1.20.0]
	at ...consultest.HelloServiceGrpc$HelloServiceBlockingStub.getGreeting(HelloServiceGrpc.java:157) ~[classes/:na]
	at ...consulclient.HelloClient.sayHello(HelloClient.java:35) ~[classes/:na]
...
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.36.Final.jar:4.1.36.Final]
...
```

I debugged the hex response and got:
```
HTTP/2.0 404 Not Found
Content-Type: application/json;charset=UTF-8
Content-Length: 102
```

Removing `.usePlaintext()` is even worse:

```
2019-06-04 15:57:38.839  INFO [consul-lognet-client,,,] 1388 --- [           main] io.grpc.netty.GrpcSslContexts            : netty-tcnative unavailable (this may be normal)

java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
	at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_162]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_162]
	at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_162]
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:123) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:402) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:522) [grpc-core-1.20.0.jar:1.20.0]
	at ...consulclient.HelloClient.init(HelloClient.java:26) [classes/:na]
...

2019-06-04 15:57:38.839  INFO [consul-lognet-client,,,] 1388 --- [           main] io.grpc.netty.GrpcSslContexts            : Conscrypt not found (this may be normal)
2019-06-04 15:57:38.840  INFO [consul-lognet-client,,,] 1388 --- [           main] io.grpc.netty.GrpcSslContexts            : Jetty ALPN unavailable (this may be normal)

java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_162]
	at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_162]
	at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64) ~[grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:266) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:402) [grpc-netty-1.20.0.jar:1.20.0]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:522) [grpc-core-1.20.0.jar:1.20.0]
	at ....consulclient.HelloClient.init(HelloClient.java:26) [classes/:na]
```
Without the Spring Cloud Gateway it works, of course.

So, can you give me advise how to use the lognet grpc starter with Spring Cloud Gateway? Or is this a problem of the Spring Cloud Gateway? 

edit:
Okay, there may be a problem with [HTTP 2 support](https://github.com/spring-cloud/spring-cloud-gateway/issues/7).

**Comment by jvmlet** [comment]
What is running on ports 8762 and 27156?

**Comment by jvmlet** [comment]
Spring clod gateway supports http endpoints ONLY. Grpc will not work with SCG. Please have a look at https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot2-starter-demo/src/test/java/org/lognet/springboot/grpc/ConsulRegistrationTest.java for usage sample.
