### ISSUE TITLE
Grpc Server start fail in java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by yxia-paxos** [LogNet/grpc-spring-boot-starter#142]
Hi, I'm upgrading y grpc-spring-boot-start version from `3.1.0` to `3.2.0` (or any version after, same error)

I'm see following error on server startup:

```
java.lang.AbstractMethodError: io.grpc.internal.AbstractServerImplBuilder.buildTransportServers(Ljava/util/List;)Ljava/util/List;
	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:223) ~[grpc-core-1.19.0.jar:1.19.0]
	at org.lognet.springboot.grpc.GRpcServerRunner.run(GRpcServerRunner.java:90) ~[grpc-spring-boot-starter-3.2.0.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
```
Seems like `grpc-core-1.19.0` is having problem?

I'm using:
java: 8
spring boot: 2.1.3 RELEASE
grpc-spring-boot-start: 3.2.0

**Comment by jvmlet** [comment]
Can you please post your maven/gradle  config ?  For gradle please post the output of `gradlew dependencies` command.

**Comment by yxia-paxos** [comment]
Here's my gradle file:
```
buildscript {
    ext {
        springBootVersion = '2.1.3.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'jacoco'

ext {
    springCloudVersion = 'Finchley.RELEASE'
}
//
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-vault-dependencies:2.0.2.RELEASE"
    }
}

bootJar {
    baseName = 'XX'
}

group = 'XX'
version = '1.0.0-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator:2.1.3.RELEASE'
    implementation 'org.springframework.boot:spring-boot-starter-web:2.1.3.RELEASE'

    compile project(":proto-model")

    // gRPC server
    implementation 'io.github.lognet:grpc-spring-boot-starter:3.2.0'

    //hikariCP
    implementation("com.zaxxer:HikariCP:3.3.0")

    // mssql jdbc
    implementation("com.microsoft.sqlserver:mssql-jdbc:6.4.0.jre8")
    implementation("org.springframework.boot:spring-boot-starter-jdbc:2.1.2.RELEASE")

    // redis
    implementation("org.springframework.data:spring-data-redis:2.1.4.RELEASE")
    implementation("org.apache.commons:commons-pool2:2.6.0")
    implementation("io.lettuce:lettuce-core:5.1.3.RELEASE")

    // rabbitMQ
    implementation("org.springframework.amqp:spring-rabbit")
    compile 'org.springframework.cloud:spring-cloud-starter-openfeign'


    implementation("org.springframework.boot:spring-boot-starter-aop:2.1.2.RELEASE")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.0.3.RELEASE")

    // prometheus
    implementation("io.micrometer:micrometer-registry-prometheus:1.1.2")
    implementation("io.prometheus:simpleclient_spring_boot:0.6.0")
    implementation("io.prometheus:simpleclient:0.6.0")

    // Vault
    def vault_enabled = "$System.env.VAULT_ENABLED"
    implementation('org.springframework.cloud:spring-cloud-starter-vault-config')
    if(vault_enabled != 'false'){
        implementation('org.springframework.cloud:spring-cloud-vault-config-databases')
        implementation('org.springframework.cloud:spring-cloud-vault-config-rabbitmq')
    }

    // retry
    implementation("org.springframework.retry:spring-retry:1.2.4.RELEASE")

    compileOnly 'org.projectlombok:lombok:1.18.4'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test:2.1.2.RELEASE'
    testImplementation 'org.codehaus.groovy:groovy-all:2.5.6'
    testImplementation 'org.spockframework:spock-core:1.2-groovy-2.5'
    testImplementation 'junit:junit:4.12'
}
```

**Comment by yxia-paxos** [comment]
Dependence output is too long, I'm listing most of the grpc and spring related part here, if this is not enough i can post more.
```
+--- project :proto-model
|    +--- com.google.protobuf:protobuf-java:3.6.0
|    +--- io.grpc:grpc-protobuf:1.18.0
|    |    +--- io.grpc:grpc-core:1.18.0
|    |    |    +--- io.grpc:grpc-context:1.18.0

|    |    +--- com.google.api.grpc:proto-google-common-protos:1.12.0
|    |    \--- io.grpc:grpc-protobuf-lite:1.18.0
|    |         +--- io.grpc:grpc-core:1.18.0 (*)
|    |         +--- org.checkerframework:checker-compat-qual:2.5.2
|    |         \--- com.google.guava:guava:25.1-android (*)
|    +--- io.grpc:grpc-stub:1.18.0
|    |    \--- io.grpc:grpc-core:1.18.0 (*)
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.8 -> 2.9.0
|    \--- io.grpc:grpc-netty-shaded:1.18.0
|         \--- io.grpc:grpc-core:[1.18.0] -> 1.18.0 (*)

+--- io.github.lognet:grpc-spring-boot-starter:3.2.0
|    +--- io.grpc:grpc-netty:1.19.0
|    |    +--- io.grpc:grpc-core:[1.19.0] -> 1.19.0
|    |    |    +--- io.grpc:grpc-context:1.19.0
|    |    |    +--- com.google.code.gson:gson:2.7 -> 2.8.5
|    |    |    +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    +--- org.codehaus.mojo:animal-sniffer-annotations:1.17
|    |    |    +--- com.google.guava:guava:26.0-android (*)
|    |    |    +--- io.opencensus:opencensus-api:0.19.2
|    |    |    \--- io.opencensus:opencensus-contrib-grpc-metrics:0.19.2
|    |    |         \--- io.opencensus:opencensus-api:0.19.2
|    |    +--- io.netty:netty-codec-http2:[4.1.32.Final] -> 4.1.33.Final
|    |    |    +--- io.netty:netty-common:4.1.33.Final
|    |    |    +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.33.Final (*)
|    |    |    +--- io.netty:netty-codec:4.1.33.Final (*)
|    |    |    +--- io.netty:netty-handler:4.1.33.Final
|    |    |    |    +--- io.netty:netty-common:4.1.33.Final
|    |    |    |    +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |    |    |    +--- io.netty:netty-transport:4.1.33.Final (*)
|    |    |    |    \--- io.netty:netty-codec:4.1.33.Final (*)
|    |    |    \--- io.netty:netty-codec-http:4.1.33.Final (*)
|    |    \--- io.netty:netty-handler-proxy:4.1.32.Final -> 4.1.33.Final
|    |         +--- io.netty:netty-common:4.1.33.Final
|    |         +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |         +--- io.netty:netty-transport:4.1.33.Final (*)
|    |         +--- io.netty:netty-codec:4.1.33.Final (*)
|    |         +--- io.netty:netty-codec-socks:4.1.33.Final
|    |         |    +--- io.netty:netty-common:4.1.33.Final
|    |         |    +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |         |    +--- io.netty:netty-transport:4.1.33.Final (*)
|    |         |    \--- io.netty:netty-codec:4.1.33.Final (*)
|    |         \--- io.netty:netty-codec-http:4.1.33.Final (*)

|    +--- io.grpc:grpc-services:1.19.0
|    |    +--- io.grpc:grpc-protobuf:1.19.0
|    |    |    +--- io.grpc:grpc-core:1.19.0 (*)
|    |    |    +--- com.google.protobuf:protobuf-java:3.6.1
|    |    |    +--- com.google.guava:guava:26.0-android (*)
|    |    |    +--- com.google.api.grpc:proto-google-common-protos:1.12.0
|    |    |    \--- io.grpc:grpc-protobuf-lite:1.19.0
|    |    |         +--- io.grpc:grpc-core:1.19.0 (*)
|    |    |         \--- com.google.guava:guava:26.0-android (*)
|    |    +--- io.grpc:grpc-stub:1.19.0
|    |    |    \--- io.grpc:grpc-core:1.19.0 (*)
|    |    +--- com.google.protobuf:protobuf-java-util:3.6.1
|    |    |    +--- com.google.protobuf:protobuf-java:3.6.1
|    |    |    \--- com.google.code.gson:gson:2.7 -> 2.8.5

default - Configuration for default artifacts.
+--- project :proto-model
|    +--- com.google.protobuf:protobuf-java:3.6.0 -> 3.6.1
|    +--- io.grpc:grpc-protobuf:1.18.0 -> 1.19.0
|    |    +--- io.grpc:grpc-core:1.19.0
|    |    |    +--- io.grpc:grpc-context:1.19.0
|    |    |    +--- com.google.code.gson:gson:2.7 -> 2.8.5
|    |    |    +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    +--- org.codehaus.mojo:animal-sniffer-annotations:1.17
|    |    |    +--- com.google.guava:guava:26.0-android
|    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.1.3 -> 2.2.0
|    |    |    |    +--- com.google.j2objc:j2objc-annotations:1.1
|    |    |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14 -> 1.17
|    |    |    +--- io.opencensus:opencensus-api:0.19.2
|    |    |    \--- io.opencensus:opencensus-contrib-grpc-metrics:0.19.2
|    |    |         \--- io.opencensus:opencensus-api:0.19.2
|    |    +--- com.google.protobuf:protobuf-java:3.6.1
|    |    +--- com.google.guava:guava:26.0-android (*)
|    |    +--- com.google.api.grpc:proto-google-common-protos:1.12.0
|    |    \--- io.grpc:grpc-protobuf-lite:1.19.0
|    |         +--- io.grpc:grpc-core:1.19.0 (*)
|    |         \--- com.google.guava:guava:26.0-android (*)
|    +--- io.grpc:grpc-stub:1.18.0 -> 1.19.0
|    |    \--- io.grpc:grpc-core:1.19.0 (*)
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.8 -> 2.9.0
|    \--- io.grpc:grpc-netty-shaded:1.18.0
|         \--- io.grpc:grpc-core:[1.18.0] -> 1.19.0 (*)

+--- io.github.lognet:grpc-spring-boot-starter:3.2.0
|    +--- io.grpc:grpc-netty:1.19.0
|    |    +--- io.grpc:grpc-core:[1.19.0] -> 1.19.0 (*)
|    |    +--- io.netty:netty-codec-http2:[4.1.32.Final] -> 4.1.33.Final
|    |    |    +--- io.netty:netty-common:4.1.33.Final
|    |    |    +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.33.Final (*)
|    |    |    +--- io.netty:netty-codec:4.1.33.Final (*)
|    |    |    +--- io.netty:netty-handler:4.1.33.Final
|    |    |    |    +--- io.netty:netty-common:4.1.33.Final
|    |    |    |    +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |    |    |    +--- io.netty:netty-transport:4.1.33.Final (*)
|    |    |    |    \--- io.netty:netty-codec:4.1.33.Final (*)
|    |    |    \--- io.netty:netty-codec-http:4.1.33.Final (*)
|    |    \--- io.netty:netty-handler-proxy:4.1.32.Final -> 4.1.33.Final
|    |         +--- io.netty:netty-common:4.1.33.Final
|    |         +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |         +--- io.netty:netty-transport:4.1.33.Final (*)
|    |         +--- io.netty:netty-codec:4.1.33.Final (*)
|    |         +--- io.netty:netty-codec-socks:4.1.33.Final
|    |         |    +--- io.netty:netty-common:4.1.33.Final
|    |         |    +--- io.netty:netty-buffer:4.1.33.Final (*)
|    |         |    +--- io.netty:netty-transport:4.1.33.Final (*)
|    |         |    \--- io.netty:netty-codec:4.1.33.Final (*)
|    |         \--- io.netty:netty-codec-http:4.1.33.Final (*)
|    +--- io.grpc:grpc-services:1.19.0
|    |    +--- io.grpc:grpc-protobuf:1.19.0 (*)
|    |    +--- io.grpc:grpc-stub:1.19.0 (*)
|    |    +--- com.google.protobuf:protobuf-java-util:3.6.1
|    |    |    +--- com.google.protobuf:protobuf-java:3.6.1
|    |    |    \--- com.google.code.gson:gson:2.7 -> 2.8.5
|    |    \--- com.google.re2j:re2j:1.2
|    \--- org.springframework.boot:spring-boot-starter:1.5.13.RELEASE -> 2.1.3.RELEASE (*)
```

**Comment by yxia-paxos** [comment]
Forgot to mention but i have a sub-project inside it which has the following dependencies:
```
dependencies {
    implementation 'com.google.protobuf:protobuf-java:3.6.0'
    implementation 'io.grpc:grpc-protobuf:1.18.0'
    implementation 'io.grpc:grpc-stub:1.18.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.9.8'
    runtimeOnly "io.grpc:grpc-netty-shaded:1.18.0"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compileOnly 'org.projectlombok:lombok:1.18.4'
    protobuf files('src/main/pax/')
}
```

**Comment by yxia-paxos** [comment]
nvm, I changed the all grpc dependencies in sub-project to `1.19.0` and it worked! Closing the issue and keep the comment here in case anyone else run into the same problem

**Comment by jvmlet** [comment]
Yes, you had both io.grpc:grpc-core:[1.19.0]  and 1.18.0 in you class path. Gradle should have upgraded 18 to 19. Not sure why it hasn't...
