### ISSUE TITLE
how to fix : Getting error for memory maxout during server streaming

### ISSUE THREAD

**Issue by yogesh-gondalkar** [LogNet/grpc-spring-boot-starter#153]
I have a method as follows : 
```
	public void getData(DataRequest request, StreamObserver<DataResponse> responseObserver) {
		log.info("server received with id = {0} and cob_id = {1}", request.getName(),request.getCobId());
		String query = queryService.getAtlasDataQuery(request.getName(), request.getCobId());
		jdbcTemplate.setFetchSize(1000);
		jdbcTemplate.query(query,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet resultSet) throws SQLException {
				while (resultSet.next()) {
					//String jsonResponse = new Gson().toString();
					//String id = resultSet.getString("POSITION_ID");
					String resultArr = null;
					try {
						resultArr = convertToJSONArray(resultSet).toString();
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					DataResponse dataResponse = DataResponse.newBuilder().setResponse(resultArr).build();
					responseObserver.onNext(dataResponse);
				}
			}
		});
	    responseObserver.onCompleted();
	}
```
This method essentially reads a DB View and fetch 2.1 million records which I am trying to stream to client via gRPC call. I get following exception on doing it . Can you please assist .

2020-07-28 10:32:24.425  INFO 18812 --- [ault-executor-0] c.a.d.grpc.server.GetDataImpl            : server received with id = {0} and cob_id = {1}
Exception in thread "grpc-default-executor-0" io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1056964887, max: 1073741824)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:121)

**Comment by jvmlet** [comment]
Sorry, I don't see how this is related to the starter. I would suggest to run your code that fetches and processes result set as standalone unit test to deal with it.
