### ISSUE TITLE
Problem of shutting down operation.

### ISSUE THREAD

**Issue by NeptuneNeptune** [LogNet/grpc-spring-boot-starter#170]
My test code:
```java
@Service
public class TestService {
    @Resource
    private EurekaClient client;

    @Scheduled(fixedDelay = 10000)
    public void test() {
        final InstanceInfo instanceInfo = client.getNextServerFromEureka("automated-server", false);
        final ManagedChannel channel = ManagedChannelBuilder.forAddress(instanceInfo.getIPAddr(), instanceInfo.getSecurePort())
                .usePlaintext()
                .build();
        RequestGrpc.RequestBlockingStub stub = RequestGrpc.newBlockingStub(channel);
        SMessage message = stub.report(CMessage.newBuilder().setMsg("hello").build());
        System.out.println(message);
    }

    @PostConstruct
    public void test1() {
        final InstanceInfo instanceInfo = client.getNextServerFromEureka("automated-server", false);
        final ManagedChannel channel = ManagedChannelBuilder.forAddress(instanceInfo.getIPAddr(), instanceInfo.getSecurePort())
                .usePlaintext().build();
        StreamGrpc.StreamStub stub = StreamGrpc.newStub(channel);
        stub.serverStream(CMessage.newBuilder().setMsg("hello").build(), new StreamObserver<SMessage>() {
            @Override
            public void onNext(SMessage sMessage) {
                System.out.println(sMessage);
            }

            @Override
            public void onError(Throwable throwable) {
                System.err.println(throwable.getMessage());
            }

            @Override
            public void onCompleted() {
                System.out.println("closed");
            }
        });
    }
}
```
when there is just one method, it will not throw exception. However, when there are two methods, it will throw exception like the flowing message:
```shell
2020-12-22 17:15:19.779 ERROR 14708 --- [   scheduling-1] i.g.i.ManagedChannelOrphanWrapper        : *~*~*~ Channel ManagedChannelImpl{logId=1, target=172.16.129.111:3333} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.

java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:596) ~[grpc-core-1.33.0.jar:1.33.0]
......
```
Could you please help me to solve this problem? Thank you!

**Comment by jvmlet** [comment]
**Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.**

**Comment by NeptuneNeptune** [comment]
Thank you for your suggestion, but I want one of the channel to be keep-alive because I want to push message back to the client, so I can't close it. Another channel I will close. How can I create two channels that don't interfere with each other?

**Comment by jvmlet** [comment]
First, please move to discussions, not issues.
Are  you talking about client side managed channel ?
