### ISSUE TITLE
GrpcSecurityConfigurerAdapter initialization failure without spring-security-oauth2-resource-server

### ISSUE THREAD

**Issue by kshchepanovskyi** [LogNet/grpc-spring-boot-starter#176]
Issue
===

`GrpcSecurityConfigurerAdapter` fails to initialize when it is in use, but module has no `implementation` dependency on `org.springframework.security:spring-security-oauth2-resource-server`.

Without this dependency application fails to start:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springGrpcSecurityInterceptor' defined in class path resource [org/lognet/springboot/grpc/security/GrpcSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.grpc.ServerInterceptor]: Factory method 'springGrpcSecurityInterceptor' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/oauth2/core/OAuth2Error
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-5.3.1.jar:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.1.jar:5.3.1]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
        at com.livevision.GameServiceApplication.main(GameServiceApplication.java:28) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[application/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.grpc.ServerInterceptor]: Factory method 'springGrpcSecurityInterceptor' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/oauth2/core/OAuth2Error
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.3.1.jar:5.3.1]
        ... 28 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/oauth2/core/OAuth2Error
        at org.lognet.springboot.grpc.security.GrpcSecurityConfigurerAdapter.init(GrpcSecurityConfigurerAdapter.java:43) ~[grpc-spring-boot-starter-4.2.3.jar:na]
        at org.lognet.springboot.grpc.security.GrpcSecurityConfigurerAdapter.init(GrpcSecurityConfigurerAdapter.java:12) ~[grpc-spring-boot-starter-4.2.3.jar:na]
        at com.livevision.player.auth.GrpcSecurityConfiguration$$EnhancerBySpringCGLIB$$cd8e81fc.init(<generated>) ~[classes/:na]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:338) ~[spring-security-config-5.4.1.jar:5.4.1]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:300) ~[spring-security-config-5.4.1.jar:5.4.1]
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38) ~[spring-security-config-5.4.1.jar:5.4.1]
        at org.lognet.springboot.grpc.security.GrpcSecurityConfiguration.springGrpcSecurityInterceptor(GrpcSecurityConfiguration.java:36) ~[grpc-spring-boot-starter-4.2.3.jar:na]
        at org.lognet.springboot.grpc.security.GrpcSecurityConfiguration$$EnhancerBySpringCGLIB$$60e5c040.CGLIB$springGrpcSecurityInterceptor$1(<generated>) ~[grpc-spring-boot-starter-4.2.3.jar:na]
        at org.lognet.springboot.grpc.security.GrpcSecurityConfiguration$$EnhancerBySpringCGLIB$$60e5c040$$FastClassBySpringCGLIB$$acdcb236.invoke(<generated>) ~[grpc-spring-boot-starter-4.2.3.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.1.jar:5.3.1]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.1.jar:5.3.1]
        at org.lognet.springboot.grpc.security.GrpcSecurityConfiguration$$EnhancerBySpringCGLIB$$60e5c040.springGrpcSecurityInterceptor(<generated>) ~[grpc-spring-boot-starter-4.2.3.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.1.jar:5.3.1]
        ... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.security.oauth2.core.OAuth2Error
        at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:135) ~[application/:na]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        ... 46 common frames omitted
```

Workaround
========

In order to make service work, I added following line to build.gradle:

```gradle
dependencies {
    implementation 'org.springframework.security:spring-security-oauth2-resource-server'
}
```

Affected versions
===========

4.4.2 and earlier.

**Comment by kshchepanovskyi** [comment]
We reproduced it on linux machine. However, somehow it worked on windows machine. It might be that there's  something JDK-specific.

**Comment by jvmlet** [comment]
It's on purpose. If you use `GrpcSecurityConfigurerAdapter`, you have to bring in the required dependency (as described in read). Otherwise  you will be pulling transitive dependencies of the stuff you don't need and use.
If  your app fails to start with this error and you DON'T define `GrpcSecurityConfigurerAdapter` feel free to reopen this issue.

**Comment by kshchepanovskyi** [comment]
Sorry, probably I forgot to mention that we use "Custom" (according to https://github.com/LogNet/grpc-spring-boot-starter#61-setup) schema. 
In our case application does not use OAuth2, so it should not depend on `org.springframework.security:spring-security-oauth2-resource-server`.

**Comment by jvmlet** [comment]
Please post your adapters code

**Comment by kshchepanovskyi** [comment]
```java
import org.apache.commons.lang.StringUtils;
import org.lognet.springboot.grpc.security.EnableGrpcSecurity;
import org.lognet.springboot.grpc.security.GrpcSecurity;
import org.lognet.springboot.grpc.security.GrpcSecurityConfigurerAdapter;

import java.util.Optional;

@EnableGrpcSecurity
public class GrpcSecurityConfiguration extends GrpcSecurityConfigurerAdapter {

    private final PlayerTokenAuthenticationProvider playerTokenAuthenticationProvider;

    public GrpcSecurityConfiguration(PlayerTokenAuthenticationProvider playerTokenAuthenticationProvider) {
        this.playerTokenAuthenticationProvider = playerTokenAuthenticationProvider;
    }

    @Override
    public void configure(GrpcSecurity builder) {
        builder
                .authenticationSchemeSelector(authorization -> {
                    String token = authorization.toString();
                    return StringUtils.isBlank(token) ? Optional.empty() : Optional.of(new PlayerTokenAuthentication(token));
                })
                .authenticationProvider(playerTokenAuthenticationProvider);
    }
}
```

`PlayerTokenAuthenticationProvider` checks if token provided by client in headers is present in DB.

**Comment by kshchepanovskyi** [comment]
In the `org.lognet.springboot.grpc.security.GrpcSecurityConfigurerAdapter#init(GrpcSecurity builder)` we have following line:

```
authenticationSchemeService.register(new BearerTokenAuthSchemeSelector());
```

It is always invoked. `BearerTokenAuthSchemeSelector` imports some of stuff from spring-security-oauth:

```
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.security.oauth2.server.resource.BearerTokenAuthenticationToken;
import org.springframework.security.oauth2.server.resource.BearerTokenError;
```

As a result, if project does not have oauth2 dependencies, it will fail.

Probably it makes sense to check if we have oauth2 dependencies on classpath before invoking it (somehow check if classes can be loaded).

**Comment by jvmlet** [comment]
I'm thinking about @ConditionalOnClass bean to configure bearer authentication. Want to avoid catching  ClassNotFoundException

**Comment by kshchepanovskyi** [comment]
> I'm thinking about @ConditionalOnClass bean to configure default bearer authentication

It is quite challenging as `BearerTokenAuthSchemeSelector` is not a spring bean.

**Comment by jvmlet** [comment]
`4.4.7`  released, thanks @kshchepanovskyi

**Comment by kshchepanovskyi** [comment]
@jvmlet Thank you! We just upgraded dependencies, everything works fine now.
