### ISSUE TITLE
BaseEncoding::DecodingException: Invalid input length

### ISSUE THREAD

**Issue by tobq** [LogNet/grpc-spring-boot-starter#184]
I'm using `grpc-web` - proxied by Envoy - to access my (Java) GRPC backend.

When I pass the metadata: `{"Authorization-bin":"Bearer ey..."}` I get the error:
```
 java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 1513
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:219) ~[guava-29.0-android.jar:na]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcHttp2HeadersUtils$GrpcHttp2InboundHeaders.add(GrpcHttp2HeadersUtils.java:119) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcHttp2HeadersUtils$GrpcHttp2RequestHeaders.add(GrpcHttp2HeadersUtils.java:305) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcHttp2HeadersUtils$GrpcHttp2RequestHeaders.add(GrpcHttp2HeadersUtils.java:276) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.HpackDecoder$Http2HeadersSink.appendToHeaderList(HpackDecoder.java:571) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.HpackDecoder.insertHeader(HpackDecoder.java:431) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.HpackDecoder.decode(HpackDecoder.java:292) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.HpackDecoder.decode(HpackDecoder.java:129) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2HeadersDecoder.decodeHeaders(DefaultHttp2HeadersDecoder.java:126) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	... 28 common frames omitted
```

I think this is an issue with grpc-spring-boot-start, as passing this same meta using the "Authorization" key instead works fine (I check this using a ServerInterceptor - the data is getting through to the server fine).

When I change the key to "Authorization-bin" things break. What is confusing is that when I send this metadata using BloomRPC it works fine

**Comment by jvmlet** [comment]
As stated in readme, `Authorization-bin` uses binary marshaller.
