### ISSUE TITLE
[native image] Could not find reflection configuration resource "META-INF/native-image/io.github.lognet/grpc-spring-boot-starter/reflection-config.json"

### ISSUE THREAD

**Issue by kim-ddongs** [LogNet/grpc-spring-boot-starter#337]
Hi,

I using this framework for grpc protocol support.

Meanwhile, i face problem when execute task bootBuildImage for build native image.

Buildpack is no problem. but graalvm steps have a problem.

Maybe, cause is 'grpc-spring-boot-starter' native-image.properties have some arguments that is "-H:ReflectionConfigurationResources=${.}/reflection-config.json"

How to solve this problem?

Thanks in advance.

version : 5.0.0

native build error log
```
    [creator]     [1/7] Initializing...                                            (0.0s @ 0.59GB)
    [creator]     Error: Could not find reflection configuration resource "META-INF/native-image/io.github.lognet/grpc-spring-boot-starter/reflection-config.json".
    [creator]     com.oracle.svm.core.util.UserError$UserException: Could not find reflection configuration resource "META-INF/native-image/io.github.lognet/grpc-spring-boot-starter/reflection-config.json".
    [creator]     	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
    [creator]     	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$2(ConfigurationParserUtils.java:96)
    [creator]     	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
    [creator]     	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    [creator]     	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    [creator]     	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    [creator]     	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
    [creator]     	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
    [creator]     	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    [creator]     	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    [creator]     	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    [creator]     	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [creator]     	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
    [creator]     	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
    [creator]     	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:113)
    [creator]     	at com.oracle.svm.hosted.reflect.ReflectionFeature.duringSetup(ReflectionFeature.java:232)
    [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$16(NativeImageGenerator.java:918)
    [creator]     	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
    [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:918)
    [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
    [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
    [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
    [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
    [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
    [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:610)
```

**Comment by jvmlet** [comment]
I've removed reflection config  jsin in latest build... Sorry. Will add it back

**Comment by jvmlet** [comment]
@galik-ya @kim-ddongs , please try with  `5.1.1-SNAPSHOT`

**Comment by mobileharry** [comment]
Hi,

Based on 5.1.1-SNAPSHOT, I built the project with graalvm Native and the build was succeed. But I got an run time exception as following. And, if the project is built in JVM,  it can run without error. I don't know where I did wrong. Could you please help me to figure it out?

Exception: Error creating bean with name 'collectorGRpcServiceImpl': Instantiation of supplied bean failed
Apr 12, 2023 5:34:52 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Tomcat]
2023-04-12 17:34:52.618 ERROR 2500 --- [main              ] org.springframework.boot.SpringApplication        : [820  ] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'collectorGRpcServiceImpl': Instantiation of supplied bean failed

**Comment by dktapps** [comment]
Having the same issue again with 5.2.0: Error: Could not find reflection configuration resource "META-INF/native-image/io.github.lognet/grpc-spring-boot-starter/reflection-config.json".

Is there any quick workaround I can do for this?

**Comment by jvmlet** [comment]
Hi, I've dropped this feature in 5.2.0.

**Comment by dktapps** [comment]
So is there no way to build this with GraalVM native now, or am I missing something?
