### ISSUE TITLE
Issue with reactive-grpc and the default security interceptors

### ISSUE THREAD

**Issue by sheinbergon** [LogNet/grpc-spring-boot-starter#355]
The most recent version of `reactive-grpc` 1.2.4 introduced this feature https://github.com/salesforce/reactive-grpc/pull/301
It adds method overloads for `Mono<T>` with plain `T` as input params in the base class used for gRPC server implemetnation

When trying to use this API with https://github.com/LogNet/grpc-spring-boot-starter/releases and have its security turned on, this error is thrown:

```java
...Ambiguous method <METHOD NAME> in service...
at org.lognet.springboot.grpc.GRpcServicesRegistry.descriptorToServiceMethod(GRpcServicesRegistry.java:204) ~[grpc-spring-boot-starter-5.1.1.jar:?]
	at org.springframework.util.function.SingletonSupplier.get(SingletonSupplier.java:97) ~[spring-core-6.0.8.jar:6.0.8]
	at org.lognet.springboot.grpc.GRpcServicesRegistry.getGrpServiceMethod(GRpcServicesRegistry.java:124) ~[grpc-spring-boot-starter-5.1.1.jar:?]
	at org.lognet.springboot.grpc.security.SecurityInterceptor.setupGRpcSecurityContext(SecurityInterceptor.java:261) ~[grpc-spring-boot-starter-5.1.1.jar:?]
	at org.lognet.springboot.grpc.security.SecurityInterceptor.interceptCall(SecurityInterceptor.java:143) ~[grpc-spring-boot-starter-5.1.1.jar:?]
	... 14 more
```

Looking ath the source, it just picks up on the overloaded methods and fails on ambiguoity, which makes sense.
Is there  a way to have the server deal with this issue (say, treat these methods as one)?

**Comment by jvmlet** [comment]
Thanks for reporting, will check this

**Comment by jvmlet** [comment]
@sheinbergon , please try with latest `5.1.2-SNAPSHOT`, I'll release `5.1.2` once you confirm this  working for you.

**Comment by sheinbergon** [comment]
10x. I will test and let you know

**Comment by jvmlet** [comment]
`5.1.2` is out
