### ISSUE TITLE
I want to know the error and cause of TLS settings.

### ISSUE THREAD

**Issue by seungdols** [LogNet/grpc-spring-boot-starter#367]
Hi, 

In order to create a PEM file for TLS settings in a local environment, I used [minica](https://github.com/jsha/minica).

I have set up the configuration in application.yml, but I am getting an error. What should I do?

Do you have any other settings? Should I configure the CustomServer?

The configuration is as follows:

```yml
server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:cert/minica.jks
    key-store-password: "qwe123"
    key-password: "qwe123"
    key-alias: "localhost"

grpc:
  port: 6565
  security:
    cert-chain: classpath:cert/minica.pem
    private-key: classpath:cert/minica-key.pem

spring:
  application:
    name: grpc-service

```

```kotlin
    const val kotlin = "1.8.21"
    const val kotlinCoroutine = "1.7.2"
    const val kotest = "5.6.2"
    const val kotestExtensionSpring = "1.1.3"
    const val grpcSpringBootStarter = "4.9.1"
    const val grpc = "1.50.0"
    const val protobuf = "3.23.4"
    const val grpcKotlin = "1.3.0"
    const val mockk = "1.13.5"
    const val springMockk = "4.0.2"
    const val mysqlConnector = "8.0.33"
    const val feign = "3.1.5"
```

The error message is as follows.

```text

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-07-26 14:50:53.493 ERROR 47025 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'grpcServerRunner'; nested exception is java.lang.RuntimeException: Failed to start GRPC server
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.24.jar:5.3.24]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.6.jar:2.7.6]
	at com.seungdols.company.grpc.GrpcServerApiApplicationKt.main(GrpcServerApiApplication.kt:13) ~[main/:na]
	at com.seungdols.company.grpc.GrpcServerApiApplicationKt.main(GrpcServerApiApplication.kt) ~[main/:na]
Caused by: java.lang.RuntimeException: Failed to start GRPC server
	at org.lognet.springboot.grpc.GRpcServerRunner.start(GRpcServerRunner.java:114) ~[grpc-spring-boot-starter-4.9.1.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.24.jar:5.3.24]
	... 15 common frames omitted
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid private key.
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:416) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:341) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:84) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:126) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.useTransportSecurity(NettyServerBuilder.java:713) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.useTransportSecurity(NettyServerBuilder.java:68) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at org.lognet.springboot.grpc.autoconfigure.GRpcAutoConfiguration.lambda$configurator$1(GRpcAutoConfiguration.java:148) ~[grpc-spring-boot-starter-4.9.1.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at org.lognet.springboot.grpc.autoconfigure.GRpcAutoConfiguration.lambda$configurator$3(GRpcAutoConfiguration.java:139) ~[grpc-spring-boot-starter-4.9.1.jar:na]
	at org.lognet.springboot.grpc.GRpcServerRunner.start(GRpcServerRunner.java:107) ~[grpc-spring-boot-starter-4.9.1.jar:na]
	... 16 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1155) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1134) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:414) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	... 25 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:170) ~[jdk.crypto.ec:na]
	at java.base/java.security.KeyFactory.generatePrivate(KeyFactory.java:389) ~[na:na]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1153) ~[grpc-netty-shaded-1.51.0.jar:1.51.0]
	... 27 common frames omitted
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at java.base/sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:135) ~[na:na]
	at java.base/sun.security.pkcs.PKCS8Key.<init>(PKCS8Key.java:95) ~[na:na]
	at jdk.crypto.ec/sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:75) ~[jdk.crypto.ec:na]
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:245) ~[jdk.crypto.ec:na]
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:166) ~[jdk.crypto.ec:na]
	... 29 common frames omitted
```

Do you know the cause?

**Comment by jvmlet** [comment]
No, but  I would recheck your key file :
`Input stream does not contain valid private key.`

**Comment by seungdols** [comment]
@jvmlet It was solved by applying the version of the GRPC and the version starter to the latest version.

Thank you for your kindness.

**Comment by seungdols** [comment]
I rewritten PEM Files and worked normally.
