### ISSUE TITLE
can not access context's variables

### ISSUE THREAD

**Issue by conanchen** [LogNet/grpc-spring-boot-starter#64]
Hello,

I have MyAuthInterceptor.class to put an identity into the context, and I want to access the identity from the context. Here `UserMe identity = MyAuthInterceptor.USER_IDENTITY.get();` got error, refer to below code and error message:
```
@GRpcService(interceptors = {MyAuthInterceptor.class, LogInterceptor.class})
public class MyWordService extends MyWordGrpc.MyWordImplBase {
    private final static Gson gson = new Gson();
    private static final Logger logger = Logger.getLogger(MyWordService.class.getName());

    @Autowired
    private UserWordRepository userWordRepository;

    @Override
    public void list(ListRequest request, StreamObserver<MyWordResponse> responseObserver) {
        // Access to identity.
        UserMe identity = MyAuthInterceptor.USER_IDENTITY.get();


        logger.info(String.format("list start identity=%s, request=[%s]", identity, gson.toJson(request)));

}

/** Interceptor that validates user's identity. */
class MyAuthInterceptor implements ServerInterceptor {
  public static final Context.Key<UserMe> USER_IDENTITY
      = Context.key("identity"); // "identity" is just for debugging
 
  @Override 
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call,
      Metadata headers,
      ServerCallHandler<ReqT, RespT> next) {
    // You need to implement validateIdentity 
    UserMe identity = validateIdentity(headers);
    if (identity == null) { // this is optional, depending on your needs
      // Assume user not authenticated 
      call.close(Status.UNAUTHENTICATED.withDescription("some more info"),
                 new Metadata());
      return new ServerCall.Listener() {}; 
    } 
    Context context = Context.current().withValue(USER_IDENTITY, identity);
    return Contexts.interceptCall(context, call, headers, next);
  }

  private UserMe validateIdentity(Metadata headers) {
    return new UserMe("conan");
  }
} 
```

> 

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.ditto.easyhan.ApplicationSpringBoot.main(ApplicationSpringBoot.java:72) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Failed to create interceptor instance.; nested exception is java.lang.IllegalAccessException: Class org.lognet.springboot.grpc.GRpcServerRunner can not access a member of class org.ditto.easyhan.grpc.MyAuthInterceptor with modifiers ""
	at org.lognet.springboot.grpc.GRpcServerRunner.lambda$bindInterceptors$2(GRpcServerRunner.java:110) ~[grpc-spring-boot-starter-2.1.0.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_121]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[na:1.8.0_121]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_121]
	at org.lognet.springboot.grpc.GRpcServerRunner.bindInterceptors(GRpcServerRunner.java:118) ~[grpc-spring-boot-starter-2.1.0.jar:na]
	at org.lognet.springboot.grpc.GRpcServerRunner.lambda$run$1(GRpcServerRunner.java:82) ~[grpc-spring-boot-starter-2.1.0.jar:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_121]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_121]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_121]
	at org.lognet.springboot.grpc.GRpcServerRunner.run(GRpcServerRunner.java:78) ~[grpc-spring-boot-starter-2.1.0.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	... 6 common frames omitted
Caused by: java.lang.IllegalAccessException: Class org.lognet.springboot.grpc.GRpcServerRunner can not access a member of class org.ditto.easyhan.grpc.MyAuthInterceptor with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[na:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:436) ~[na:1.8.0_121]
	at org.lognet.springboot.grpc.GRpcServerRunner.lambda$bindInterceptors$2(GRpcServerRunner.java:108) ~[grpc-spring-boot-starter-2.1.0.jar:na]
	... 30 common frames omitted

**Comment by conanchen** [comment]
not a problem,
just missed the annotaiton on MyAuthInterceptor
@Slf4j
@Component
